### ISSUE TITLE
PinePhone and Librem 5 compatibility

### ISSUE THREAD

**Issue by TechnologyClassroom** [mrbid/TuxPusher#1]
Is PinePhone and Librem 5 support planned? 1440x720 or 720x1440 depending on orientation.

**Comment by mrbid** [comment]
I don't know a lot about PinePhone or Librem, but from what I can see online the PinePhone runs Manjaro Linux right, but on an aarch/ARM platform? in theory, it should compile on that platform in the same way it will compile on a Raspberry PI right? It should compile with gcc `gcc main.c glad_gl.c -I inc -Ofast -lglfw -lm -o tux`. Let me know how that goes, and I will see what I can do to assist getting the game to run on that platform.

Additionally I could release the game as an Emscripten port like I did with https://SeaPusher.com, there are some downsides to this, such as it runs in the web browser and I don't think native MSAA support in GLFW will work, but usually phone display pixel density is high enough that edge aliasing is not usually a problem?

There is also the problem of how the phone translates touch input, at the moment I have not added any touch input to the game and it seems like [GLFW does not explicitly support touch events](https://www.glfw.org/docs/3.3/input_guide.html) but usually mobiles map touch input to mouse input anyway - even so if this is not the case I can easily port this game to SDL2 where touch events are explicitly supported so if you do get it to compile natively and input is not working let me know and I can spin an SDL2 port no problem.

I'm a bit out of touch when it comes to mobile phones so bear with me, but this sounds achievable.

**Comment by TechnologyClassroom** [comment]
Manjaro is one option for PinePhone and Mobian (Debian Sid) is another popular choice. PureOS (Debian) is the default on Librem 5. Phosh (GNOME 3) is one of the most popular desktop environments.

Architecture, touch support, and resolution are the key factors beyond dependencies. Touch support might work out of the box like mouse clicks.

**Comment by mrbid** [comment]
I just added a WebGL build here; https://mrbid.github.io/tuxpusher/

Is the input working on your mobile device? To place a coin I think you will need to press and then drag the coin into place, and then tapping anywhere on screen should release it from the last position you tap+dragged to.

I tried to compile with `aarch64-linux-gnu-gcc` on Ubuntu but I had an issue with the `-lglfw` library, looks like I will need to manually compile glfw3 for the target platform aarch64, I will see if I can launch PinePhone in a VM and compile with the libglfw3 package presumably provided by the package manager on that platform.

**Comment by TechnologyClassroom** [comment]
I'll give it a try.

Purism wrote some [doc and provides qemu images](https://developer.puri.sm/Librem5/Development_Environment/Boards/qemu.html) to test in a VM. I don't know of anything like that for Pinephone's operating systems yet.

**Comment by TechnologyClassroom** [comment]
Good news! TuxPusher builds on PureOS and touch works!

```
sudo apt update
sudo apt install -y git gcc libglfw3-dev
git clone https://github.com/mrbid/TuxPusher
cd TuxPusher
gcc main.c glad_gl.c -I inc -Ofast -lglfw -lm -o tux
./tux
```

The resolution is distorted I think, but it technically plays in both vertical and horizontal orientations. I took screenshots of both. I'll upload them tonight or tomorrow if I can.

**Comment by TechnologyClassroom** [comment]
![20230111_03h00m04s_grim](https://user-images.githubusercontent.com/14501791/211710507-1aaabdc2-0d8c-4989-88d3-07096066a5b8.png)

![20230111_03h00m59s_grim](https://user-images.githubusercontent.com/14501791/211710439-fe4d875f-49e3-4ecc-90a9-dc3c3aa9e9bb.png)

**Comment by TechnologyClassroom** [comment]
The text at the end is not legible in vertical view. I can sort of make it out in horizontal that I need to tap to play again. Not sure if there was a score displayed. I should have taken more screenshots, but I forgot. Other than that, it works very well. Smooth gameplay. Very fast compile time.

Bravo! Well done!

**Comment by Danct12** [comment]
The game being blurry might have to do with GLFW running on X11 backend, I think you can try switching glfw lib to Wayland to have it running natively.

**Comment by mrbid** [comment]
> The text at the end is not legible in vertical view. I can sort of make it out in horizontal that I need to tap to play again. Not sure if there was a score displayed. I should have taken more screenshots, but I forgot. Other than that, it works very well. Smooth gameplay. Very fast compile time.
> 
> Bravo! Well done!

Appreciated thank you, there's no score or hud at the moment and I have to re-do that end game screen, but this is something I will be tackling in the coming days.

With the vertical squishing, that is controlled on line 1043 when window height is more than window width, in the mean time this can be tweaked for a slightly better aspect if desired. I will pay some attention to this for the next release.
https://github.com/mrbid/TuxPusher/blob/main/main.c#L1043

Nice work on getting this compiled!
