### ISSUE TITLE
GLES support

### ISSUE THREAD

**Issue by Danct12** [mrbid/TuxPusher#2]
Having GLES support would be nice for running the game on an ARM SBC where Full OpenGL doesn't exist.

**Comment by mrbid** [comment]
Hey, the game is designed with GLES in mind, as it is made to the WebGL 1.0 spec, all sharers are GLSL 1.0 so it should compile just fine, for example I can release a SDL version that uses the "SDL_opengles2.h" header if that helps?

Also just released a WebGL/WebASM version at; https://tuxpusher.github.io

**Comment by Danct12** [comment]
Yes, it compile perfectly fine, however for some reason I cannot get it to use GLES even though I made change to the source code.

Maybe this is a GLFW bug of some sort? I tested this on Ubuntu 22.10 on an Orange Pi 5 SBC.

**Comment by mrbid** [comment]
Yes I think this may be related to GLFW, I will have the SDL2 release up within the hour.

**Comment by mrbid** [comment]
Here let me know if this world a little better for you  https://github.com/mrbid/TuxPusher/tree/main/TuxPusher_SDL

**Comment by Danct12** [comment]
Thank you! However you need to change the GL profile to `SDL_GL_CONTEXT_PROFILE_ES` before the game can work on GLES.

Rockchip's Mali driver shows some info about the driver itself when a program tries to use GLES.

![Screenshot_2023-01-11_20-03-53](https://user-images.githubusercontent.com/19162768/211813593-04fad48a-5a02-4e74-8e24-b90b4fef1e39.png)


```
diff --git a/TuxPusher_SDL/main.c b/TuxPusher_SDL/main.c
index 38c80f9..e003615 100644
--- a/TuxPusher_SDL/main.c
+++ b/TuxPusher_SDL/main.c
@@ -1175,6 +1175,7 @@ int main(int argc, char** argv)
         fprintf(stderr, "ERROR: SDL_Init(): %s\n", SDL_GetError());
         return 1;
     }
+    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
     SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 1);
     SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, msaa);
     SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
```

**Comment by mrbid** [comment]
Thank you Danct12 I have updated the [main.c](https://github.com/mrbid/TuxPusher/blob/main/TuxPusher_SDL/main.c#L1182) file with the context profile attribute. I am glad it is now working! I will probably phase out the GLFW build eventually as SDL seems generally less problematic.

**Comment by Danct12** [comment]
You're welcome! Thank you for your work.
